### ISSUE TITLE
Doe een testrun

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/minecraft_quest#1]
Zaterdag 30 mei 10:00-20:00.

 * Scheidsrechters: ik en @Joshua260403 (en evt. meer)
 * Moderators: alle scheidsrechters

Server:

 djog.hosthorde.net

Teams (nieuwe aanmelding = volgende plek):

Rood|Blauw
---|---
Rijk|Kyrill

**Comment by richelbilderbeek** [comment]
```
> ik heb een goed alternatief voor de skins. Minecraft heeft namelijken teams command waarmee je makkelijk verschillende teams kan aanmaken. Dan kan je bijvoorbeeld  instellen dat het ene team een Rode en het andere Team een blauwe naam krijgt. Voorbeeld: Zo maak je een team aan: /teams add rood "Team Rood"  Zo zet je de naamkleur op rood: /team modify rood color red Zo voeg je een prefix toe: /team modify rood prefix "[ROOD] " En zo voeg je iemand toe aan het team: /team join rood spelernaam. Je kan ook instellen dat teamleden elkaar niet kunnen doodmaken: /team modify rood friendlyFire false
```

**Comment by dandanthedev** [comment]
Kan ik ook moderator worden @richelbilderbeek ? Ik host de server namelijk

**Comment by richelbilderbeek** [comment]
Supergraag zelfs! 

Wil je ook spelen? 

 * Zo ja, dan ben je moderator tot het spel begint
 * Zo nee, dan ga ik je vragen mee te doen als scheidsrechter met mij en Joshua

**Comment by dandanthedev** [comment]
Ik hoef niet mee te spelen, ben ook de server hoster dus is handig als ik daar alle tijd aan kan besteden

**Comment by richelbilderbeek** [comment]
Mooi, welkom in het team moderators (ik, Joshua en jij). Wil je ook scheidsrechter zijn?

**Comment by dandanthedev** [comment]
nee, ik zorg wel alleen voor de werking van alles

**Comment by richelbilderbeek** [comment]
Dat is prima, alvast bedankt voor je hulp!

**Comment by rijkvp** [comment]
@richelbilderbeek mag ik moderator zijn tot dat de game begint? Ik heb Daan al geholpen bij de plugins dus ben al soort van moderator. Ik hoef verder geen scheidsrechter te zijn etc. Wat doen scheidsrechters eigenlijk precies naast het rond lopen?

**Comment by richelbilderbeek** [comment]
Hoi Rijk, top, bij deze ben je moderator tot de game begint!

Een scheidsrechter loopt vooral rond en maakt de rotbeslissingen, mocht het nodig zijn zelf dat kids gebanned worden (alleen ik mag dat).

**Comment by dandanthedev** [comment]
Voor mensen bannen heb je dan wel weer commandos nodig, ik dacht dat we zonder plugins gingen doen? :)

**Comment by richelbilderbeek** [comment]
Ik kan dat altijd prima op een aternos server. Kan dat bij jou niet dan?

**Comment by dandanthedev** [comment]
kan ook wel op deze server, heb nu de permissies goed ingesteld,
je kan nu alleen maar normale dingen doen
moderators alleen hebben toegang tot een paar commandos
en we hebben ook een skywars gamemode die we handmatig aanzetten!
Dus,
Is dit een goede server?

**Comment by dandanthedev** [comment]
de server staat aan, dus je kan joinen: djog.hosthorde.net
(heb richelbilderbeek gewhitelist, hoop dat dat goed is)

**Comment by dandanthedev** [comment]
ik heb je even rood rank gegeven, dan kan je testen hoe het is als normale speler,
zeg het maar als je de moderator rank wil hebben!

**Comment by richelbilderbeek** [comment]
@daantje1: je bent geweldig! Ik ga vanavond even kijken, maar ik geloof nu al dat je een top-moderator bent :+1:

**Comment by dandanthedev** [comment]
Yay

**Comment by HexiDev** [comment]
YaY

**Comment by rijkvp** [comment]
Testrun was geslaagd
