### ISSUE TITLE
Poll: role of teamcaptain

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/minecraft_quest#11]
The goal of a teamcaptain is to guide his/her players to work together. 

If a teamcaptain that cannot modify the world, for sure the regular team members need to do the work. We can make the teamcaptain invisible and flying as well, as to best help the team work together.

But one could also argue that a teamcaptain should have the same setup as regular players and being able to be an exemplary team member. Problem is that it gets possible that the teamcaptain does most of the work him/herself and the game becomes more a match between two teamcaptains 

So, what is best?

Teamcaptain cannot change the world:

 * Pro: team must definitely work together and the teamcaptain can focus on that
 * Con: it may be more dull for the person playing the captain

Teamcaptain is regular player:
 * Pro: more fun for the person being teamcaptain
 * Con: it is possible that the teamcaptain does most of the work him/herself and the game becomes more a match between two teamcaptains

I will setup a poll.

**Comment by richelbilderbeek** [comment]
@rijkvp and @Joshua260403, as the teamcaptains for The Netherlands, what is your take on this? Especially with Rijk being a speedrunner, how to ensure (1) it is a team sports, (2) the game is fair?

Note that -would the 'teamcaptain is a ghost' option be picked, you can always become a 'regular' team member, in case you want to play as well.  

I will also ask Egon, the Swedish teamcaptain for his idea.

Of couse, the Discord is a fine place to discuss as well, I will copy text from the Discord to here when needed, so that this Issue is discussed pseudo-publically :-)

**Comment by richelbilderbeek** [comment]
Reply from Egon:

> Regarding the setup for team captain im not really sure what would be the best way to execute it but personally id enjoy it if i got to play XD. But i can see both sides, im pretty much fine either way.

So that is one vote for teamcaptains should play together with the team :-)

**Comment by rijkvp** [comment]
I prefer being a regular player as well. I don't think the captian can do everything himself. In my experience, you spend a lot of time leading your team members if you want to win because you have to divide up the tasks. The team captian should walk arround as a regular player and collect the items and support them.

**Comment by richelbilderbeek** [comment]
With both a Swedish and Dutch captain having shared their opinions, let's make that teamcaptain a regular player :-)

Thanks to both!
