### ISSUE TITLE
When will the game be played?

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/minecraft_quest#8]
Needs to figure out school holidays in The Netherlands and Sweden :-)

**Comment by rijkvp** [comment]
On the following website are the dates of the official Dutch summer holidays: https://www.rijksoverheid.nl/onderwerpen/schoolvakanties/zomervakantie/zomervakantie-2022.
For the North region its from 16 July to 28 August.

**Comment by rijkvp** [comment]
That's over 170 days :cry:

**Comment by richelbilderbeek** [comment]
I added this to the README. Done!
